# Generated by Django 2.1.1 on 2018-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_list',
            old_name='pub_date',
            new_name='aquisition_date',
        ),
        migrations.AddField(
            model_name='data_list',
            name='shot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='data_list',
            name='run',
            field=models.IntegerField(default=1),
        ),
    ]
