# Generated by Django 2.1.1 on 2018-10-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_auto_20181009_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_list',
            new_name='shot_information',
        ),
    ]
