# Generated by Django 2.1.1 on 2018-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_auto_20181009_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot_information',
            name='user_identifier',
            field=models.CharField(default='zero', max_length=200),
        ),
    ]
