# Generated by Django 2.1.2 on 2018-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_shot_information_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot_information',
            name='aquisition_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
