# Generated by Django 2.1.2 on 2018-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_auto_20181012_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot_information',
            name='aquisition_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
