# Generated by Django 2.1.2 on 2018-10-12 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0006_auto_20181012_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot_information',
            name='aquisition_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 10, 12, 13, 44, 54, 381311, tzinfo=utc)),
        ),
    ]
