# Generated by Django 2.1.1 on 2018-10-15 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_auto_20181012_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot_information',
            old_name='shot',
            new_name='shot_number',
        ),
        migrations.AlterField(
            model_name='shot_information',
            name='aquisition_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 10, 15, 13, 58, 47, 75721, tzinfo=utc)),
        ),
    ]
